Adding in memory table
raw-labs/das-mock pull request #3
Opened 2024-09-13 09:28 UTC by Alexzerntev

- Added in memory table that supports CRUD
- Added inital readme

2024-09-13 09:39 UTC, miguelbranco80 requested changes
Some suggestions

2024-09-13 09:39 UTC, miguelbranco80 commented on src/main/scala/com/rawlabs/das/mock/DASMockStorage.scala
> +  def iterator: Iterator[Row] = treeMap.valuesIterator
Interesting case. How to give back an iterator if the underlying structure can change?
Clone the treeMap and give an iterator out of the cloned one.

2024-09-13 09:39 UTC, miguelbranco80 commented on src/main/scala/com/rawlabs/das/mock/DASMockStorage.scala
> +    private val treeMap: mutable.TreeMap[String, Row] = new mutable.TreeMap[String, Row]()
Move this to the body of the class.
Also, create a lock object.

```scala
class DASMockStorage(val key: String) {

  private val treeMap = new mutable.TreeMap[String, Row]()
  private val treeMapLock = new Object

  def add(row: Row): Row = {
    treeMapLock.synchronized {
      treeMap.put(row.getDataMap.get(key).getInt.getV.toString, row)
      row
    }
  }
  ... <same elsewhere>

```

2024-09-13 09:39 UTC, miguelbranco80 commented on src/main/scala/com/rawlabs/das/mock/DASMockTable.scala
> +  override def execute(
Add a comment saying quals and columsn are being ignored (PostgreSQL does it anyway).
But maybeLimit is being applied.

2024-09-13 09:39 UTC, miguelbranco80 commented on src/main/scala/com/rawlabs/das/mock/DASMockInMemoryTable.scala
> +  override def execute(
Add a comment saying quals, columns and maybeLimit are being ignored.

2024-09-13 09:39 UTC, miguelbranco80 commented on src/main/scala/com/rawlabs/das/mock/DASMockInMemoryTable.scala
> +    new DASExecuteResult {
This seems wrong. If you say you support sort orders, you must implement sort orders here.
Did you try a query with various ORDER BY ASC and DESC and see if it behaves? I suspect it's broken.

2024-09-13 09:39 UTC, miguelbranco80 commented on README.md
> +```DROP SERVER multicorn_das CASCADE;
```sql

2024-09-13 09:39 UTC, miguelbranco80 commented on README.md
> +- [multicorn2](https://github.com/raw-labs/multicorn2)
multicorn2 RAW Labs Fork

2024-09-13 09:39 UTC, miguelbranco80 commented on src/main/scala/com/rawlabs/das/mock/DASMock.scala
> +  }
?

2024-09-13 09:39 UTC, miguelbranco80 commented on src/main/scala/com/rawlabs/das/mock/DASMock.scala
> +  }
Why don't you add this to the class constructor?

2024-11-05 08:20 UTC, bgaidioz approved these changes

2024-11-05 08:25 UTC, miguelbranco80 approved these changes

2024-11-05 08:26 UTC, merged